dataset:
  train:
    format: ase_db
    src:
      - /data/mptrj/train/train_mptrj.aselmdb
    a2g_args: { r_energy: True, r_forces: True, r_stress: True}
    transforms:
      decompose_tensor:
        tensor: stress
        rank: 2
        decomposition:
          stress_isotropic:
            irrep_dim: 0
          stress_anisotropic:
            irrep_dim: 2
      normalizer:
        file: /data/mptrj/normalizers.pt
      element_references:
        file: /data/mptrj/element_references.pt

  val:
    format: ase_db
    src:
      - /data/mptrj/val/val_mptrj.aselmdb
    a2g_args: { r_energy: True, r_forces: True, r_stress: True}
