includes:
  - configs/s2ef/MPTrj/base.yml

trainer: equiformerv2_forces

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 20
  - stress_isotropic:
      fn: mae
      coefficient: 5
  - stress_anisotropic:
      fn: mae
      reduction: mean
      coefficient: 5

evaluation_metrics:
  primary_metric: energy_mae
  metrics:
    energy:
      - mae
      - per_atom_mae
    forces:
      - mae
      - forcesx_mae
      - forcesy_mae
      - forcesz_mae
      - cosine_similarity
    stress:
      - mae
    stress_isotropic:
      - mae
    stress_anisotropic:
      - mae

outputs:
  energy:
    level: system
    property: energy
  forces:
    level: atom
    property: forces
    train_on_free_atoms: True
    eval_on_free_atoms: True
  stress:
    level: system
    property: stress
    decomposition:
      stress_isotropic:
        irrep_dim: 0
      stress_anisotropic:
        irrep_dim: 2

model:
  name: hydra
  pass_through_head_outputs: True
  otf_graph: True

  backbone:
    model: src.EScAIP.EScAIPBackbone

    # Global Configs
    activation: gelu
    direct_force: true
    hidden_size: 512
    regress_forces: true
    use_fp16_backbone: false
    batch_size: 4 ## need to be the same as optim.batch_size!!


    # Molecular Graph Configs
    enforce_max_neighbors_strictly: true
    distance_function: gaussian
    max_neighbors: 20
    max_num_elements: 96
    max_num_nodes_per_batch: 200 # Average 31.194, Max 444, use 100 for padding
    max_radius: 12.0
    otf_graph: true
    use_pbc: true
    use_pbc_single: false


    # Graph Neural Networks Configs
    atom_embedding_size: 128
    atten_name: memory_efficient
    atten_num_heads: 16
    edge_distance_embedding_size: 512
    edge_distance_expansion_size: 600
    node_direction_embedding_size: 64
    node_direction_expansion_size: 10
    num_layers: 6
    output_hidden_layer_multiplier: 2
    readout_hidden_layer_multiplier: 2
    ffn_hidden_layer_multiplier: 2
    use_angle_embedding: true


    # Regularization Configs
    atten_dropout: 0.1
    mlp_dropout: 0.05
    normalization: rmsnorm
    stochastic_depth_prob: 0.0

  heads:
    forces:
      module: src.EScAIP.EScAIPDirectForceHead
    energy:
      module: src.EScAIP.EScAIPEnergyHead
    stress:
      module: src.EScAIP.EScAIPRank2Head


optim:
  batch_size:                   4         # 6
  eval_batch_size:              4         # 6
  load_balancing: atoms
  num_workers: 0
  lr_initial:                   0.00001    # EquivormerV2 uses 0.0004 for signal gpu batch size 8

  optimizer: AdamW
  optimizer_params:
    weight_decay: 0.01
  scheduler: LambdaLR
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2
    warmup_epochs: 0.1
    lr_min_factor: 0.5         # EquivormerV2 uses 0.01

  max_epochs: 500
  clip_grad_norm: 10
  ema_decay: 0.999

  eval_every: 1000
  # checkpoint_evey: 50000

slurm:
  constraint: "volta32gb"
